# src/test/resources/application-test.yaml
spring:
  datasource:
    url: jdbc:h2:mem:catconnect;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  session:
    store-type: none         # don't start JDBC session in tests
  flyway:
    enabled: false           # (or true if your migrations are H2-compatible)
  jpa:
    hibernate:
      ddl-auto: none
