swagger: "2.0"
info:
  title: My service
  description: My service
  version: 1.0.0
host:
schemes:
  - https
paths:
  localhost:
    get:
      tags:
        - Health Check
      summary: Health Check
      description: Health Check
      operationId: healthCheck
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string